# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 2de458affade0ea99132fb1535639d4c8276f62dbd927819c861964f5dbef434425ae56845195210d0d86a09f4eb4a7445a36261255e5d31f8ba6763ed1ca31b

test:
  secret_key_base: 82fd08254c6b43d72e7c069d619d2d98e757b9a16b8fe599ecb0a3166194102d946bcc4e99c9d7b227fb528f479791c444f0323cf9e2562e0116e4525fd9554f

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
